### ISSUE TITLE
Suggestion: Provide four modules instead of checking global constants

### ISSUE THREAD

**Issue by eschnett** [J-Sarnoff/FloatHigher.jl#3]
You could provide four modules (`FloatHigher128`, `FloatHigher256`, etc.) instead of only a single one. Then there's no need for global variables that are checked when importing `FloatHigher`.

The current mechanism breaks if two Julia packages both use `FloatHigher`, but with different settings, and if someone then wants to combine these two Julia packages.

**Comment by J-Sarnoff** [comment]
In either case, I need to add promotion/conversion for the different precisions.
My inclination is to let automatic promotion select the smaller precision, as that maintains accuracy without introducing hidden assumptions.  The user could force conversion to the higher precision:
a=Float512(a)

Do you agree with the default promotion being to the smaller precision?

While splitting the modules may be a better way to go, FYI The current mechanism would not break in the circumstance you mention. This works:
UseFloat128=true
UseFloat512=true
using FloatHigher
a=Float128(128); b=Float512(512)

**Comment by J-Sarnoff** [comment]
I added mixed type conversion/promotion and an example using mixed types.

**Comment by J-Sarnoff** [comment]
Also providing types in separate modules: Floats128, Floats256, Floats512, Floats1024.
Added note about this to the README
